### ISSUE TITLE
Issue on global power formula

### ISSUE THREAD

**Issue by zzydxm** [gemforce-team/skill-allocator#1]
Hi,

I recently start to play GCCS and your guide is very helpful. However, I don't agree with you on the global power formula. Here is the right way I think:

Assume the mana gem power is M(tc, b, l, t) = TCs(tc)^2 *Bbound(b)*Leech(l)*Traps(t) and the kill gem power is K(tc, b, c, r) = TCd(tc)*TCs(tc)^3 *Bbound(b)^2 *Crit(c)*Reson(r), which is the same as you said.

In general, you will upgrade your mana gem until some time point, and then turn to upgrading your kill gem. This time point could be level 200, level 500, or level 999, but it only matters a small constant factor. So, let's say, the total time to upgrade mana gem is a fixed constant C.

Now, let's consider the time to upgrade one level (or 4 levels for 16c, 3 levels for 11c). Each time you upgrade, your upgrade price is doubled, but your mana gain speed only increased 1.5 times. This means your upgrading time is 2/1.5=1.333 times the last upgrading time. Therefore the upgrading time is a geometric progression. It is easy to show that the number of levels you can upgrade is Log(1.333,M*C), where M is the mana gem power.

On the other side, the level of the kill gem will be basically the same as the mana gem, the difference is definitely less than 5, otherwise you would rather upgrade your mana gem and finally get higher kill gem level.

By simply upgrading one level, the kill gem power becomes 2.377 times the original power, so the global power formula should be:
2.377^Log(1.333, M*C)*K = constant*[M^Log(1.333, 2.377)]*K = constant*(M^3.039)*K
, where K is the kill gem power. If we use 11c, it will be (M^3.393)*K, still much smaller than your formula.

Thanks!

**Comment by 12345ieee** [comment]
> Hi,
> 
> I recently start to play GCCS and your guide is very helpful. However, I don't agree with you on the global power formula. Here is the right way I think:

Thank you. I assume you have read the associated Skills guide, where my reasoning is detailed.
I also assume you know what GP represents, what a combine growth is and some other of the technicalities of non-standard combining.

> Assume the mana gem power is M(tc, b, l, t) = TCs(tc)^2 _Bbound(b)_Leech(l)_Traps(t) and the kill gem power is K(tc, b, c, r) = TCd(tc)_TCs(tc)^3 _Bbound(b)^2 *Crit(c)_Reson(r), which is the same as you said.

Good.

> In general, you will upgrade your mana gem until some time point, and then turn to upgrading your kill gem. This time point could be level 200, level 500, or level 999, but it only matters a small constant factor. So, let's say, the total time to upgrade mana gem is a fixed constant C.

By **level** here you mean **wave**, right?
Correct, the aim is to provide the best killgem for a given constant farming time, let's call it `C`.

> Now, let's consider the time to upgrade one level (or 4 levels for 16c, 3 levels for 11c). Each time you upgrade, your upgrade price is doubled, but your mana gain speed only increased 1.5 times.

Please, do not forcibly introduce 2c in a reasoning that has to be independent from combine method you use. Doing this only creates artifacts and imprecisions and makes it difficult to generalize.

I will change in your quotes (and make changes **bold**) all your explicit references to 2c with references to a generic combine method, which uses NC(=2 for 2c) gems, improves your gem by P(~1.5 for 2c) and has growth g=log(P)/log(NC)(~0.59 for 2c).
Same for the killgem, with increment P_k and growth gk.

I'll still assume we use only one combine method throughout the whole field, real people don't play like this (you use shorter and shorter combines as you can gather less and less mana), but the approximation is good enough.

> This means your upgrading time is **NC/P~1.3** times the last upgrading time. Therefore the upgrading time is a geometric progression. It is easy to show that the number of levels you can upgrade is **Log(NC/P, M*C)**, where M is the mana gem power.

I assume you use the `Log(base, argument)` convention.
You are not really right. as you have computed just the time necessary to do the last combine,
which is `T_n = (NC/P)^n * T_0` (`T0` goes as `1/M`) and then inverted it, but you actually needed the relation for the total time.
This is a terrible approximation when NC/P ~1, which is our case.
You need to sum the geometrical progression and invert the result.

I did it for you:
Let's define `F=NC/P=(with some algebra)=NC^(1-gm)` where `gm` is the growth of your combine method on the managem.
You get: `TT_n = (1-F^(n+1))/(1-F))*T_0`
which yields: `N = Log(F, (F-1)*C*M - 1) -1`
Now, `C*M` is a big number, we can neglect the `1` inside the logarithm and also the `1` out of the logarithm, as it's just a constant, so:
`N = Log(F, (F-1)*C*M)` which is very similar to your approximation.

> On the other side, the level of the kill gem will be basically the same as the mana gem, the difference is definitely less than 5, otherwise you would rather upgrade your mana gem and finally get higher kill gem level.

Not really (unless you're too low level, but if you are, the SP guide is still useless for you).

While you are gathering mana you just upgrade your mana gem, the expenditure on your killgem has to be insignificant (like 10 grades or so below, so that upgrading does not make a dent). This grants you the maximum mana farming speed.
When you're ready to kill you just sell your managem and build a killgem.

You've read the Extreme End Game guide, right?

We can still keep your logic, if you want, because when you've sold the managem you'll use all the mana you have to build a killgem, and you'll reasonably have at hand a small multiple of the total mana in your managems (like 1.5x - 3x) (if you had more, you'd have upgraded your managems).
This is equivalent to carrying on your killgem side by side with your managem (small multiple apart), it's just faster to do.

> By simply upgrading one level, the kill gem power becomes **P_k?=?2.377** times the original power, so the global power formula should be:

Where did you get that value for `P_k`? gemforce says `2.590533` for 2c, and I really really really trust gemforce.
Have you accounted for the fact that `BB_bonus = 1 + BB_power`, which screws the simple calculations at low gem levels?

> **P_k^Log(F, M*C)*K = constant*[M^Log(F, P_k)]*K** = constant*(M^3.039)*K

Here the (1-F) you lose in your approximation of N disappears into the constant, so this formula is right, but the numerical value is different, due to P_k, I get 3.34.

> , where K is the kill gem power. If we use 11c, it will be (M^3.393)*K, still much smaller than your formula.

So, the only difference is the exponent of M, you have `Log(F, P_k)`, I have `gk/(1-gm)`
For 2c yours yields 3.34 (when done with a correct `P_k`), mine yields 1.373/(1-0.589)=3.34.

Which is NOT surprising, as you can show with a bit of algebra that the 2 expressions are completely equivalent, just written in terms of different quantities.

The advantage of the growths approach is that you don't have to carry around the NCs and you can prove the formula even for different combine lengths for mana and killgem, something you need a bit of work to do with your approach.

> Thanks!

Thanks to you, you're probably the first person that has ever read the mathematical section of the guide.

**Comment by quinor** [comment]
> Thanks to you, you're probably the first person that has ever read the mathematical section of the guide.

Well, at least the second one as you can count me ;)

I will just add that if you are interested in the technical part of how Gemforce works, feel free to dive into it and ask questions. Maybye if you're good you'll find methods to optimize what we've done here and even if not, I'm sure it'll be lots of fun :)

**Comment by 12345ieee** [comment]
Your idea of FUN is the best, @quinor .
I actually had more minor optimizations, but it makes no sense to implement any at this point, doubling any table takes at least one month of CPU time.

Hope you had FUN reading my guide, too.

**Comment by zzydxm** [comment]
Well, I may misunderstood your gk and gm at the first time. The "killpower = M^gk" really confused me. (At beginning, I believe that building more gems is always better than upgrading gems unless the armor is too high, so I was skeptical when I saw such a large gk = 1.41. It's better to see "gk = Log(NC_k,P_k)", I think.)

It turns out our calculation is exactly the same on the result, although we use different approximation method (I assume F=NC/P is a constant, so it didn't appear in the calculation of geometric progression).

In my approach, if we want to use different combine method for mana gem and kill gem, the exponent becomes Log(NC_m/P_m, P_k)*Log(NC_k,NC_m), which is still the same as yours.

On the other hand, I just realized why I have the wrong P_k, the damage increment for kill gem is 1.58, the critical increment is 1.38, and blood bound is 1.09. My calculation for P_k is 1.58*1.38*1.09, but the correct way is 1.58*1.38*(1.09^2). I only read the head file in gemforce and did some test in game, but I didn't run the code. That's why I made this mistake.

Thanks again for your kind reply. I'm really sorry for my mistake.

**Comment by 12345ieee** [comment]
> Well, I may misunderstood your gk and gm at the first time. The "killpower = M^gk" really confused me. (At beginning, I believe that building more gems is always better than upgrading gems unless the armor is too high, so I was skeptical when I saw such a large gk = 1.41. It's better to see "gk = Log(NC_k,P_k)", I think.)

That is the definition of `gk`, but the important point there was that `M` sort of takes the role of `NC`.
In the next section it is then explained that it's actually `M^(1/(1-gm))` that takes the role of `NC`, due to managem upgrading.

Armor matters nothing here, `gk` being bigger than 1 just means that yb gems killpower grows faster than gem cost.

> It turns out our calculation is exactly the same on the result, although we use different approximation method (I assume F=NC/P is a constant, so it didn't appear in the calculation of geometric progression).
> 
> In my approach, if we want to use different combine method for mana gem and kill gem, the exponent becomes Log(NC_m/P_m, P_k)*Log(NC_k,NC_m), which is still the same as yours.

Exactly, all the `NC`s fall into their growths as they should.

> On the other hand, I just realized why I have the wrong P_k, the damage increment for kill gem is 1.58, the critical increment is 1.38, and blood bound is 1.09. My calculation for P_k is 1.58_1.38_1.09, but the correct way is 1.58_1.38_(1.09^2). I only read the head file in gemforce and did some test in game, but I didn't run the code. That's why I made this mistake.
> 
> Thanks again for your kind reply. I'm really sorry for my mistake.

No problem.
It's good to see that even approaching the problem from a completely different starting point yields the same formula, up to constants redefinition.
